name: nmap
description: A dart package that provides null map operation extension.
version: 1.0.0
repository: https://github.com/gruvw/nmap

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
