name: Dart Check CI

on: push

jobs:
  dart-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dart dependencies
        run: |
          dart --version
          dart pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Check for code errors
        run: dart analyze

      - name: Check for documentation errors
        run: dart doc

      - name: Run tests
        run: dart test
